spring:
  application:
    name: ORDER-SERVICE

  boot:
    admin:
      client:
        url: http://localhost:1111

  datasource:
    url: jdbc:mysql://localhost:3306/product_rest
    username: root
    password: Shivu@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
